package blackjack;
/**
 *
 * @author daniel
 */
public class Card {
    // This class was generated by Chat GPT
    private final String suit;
    private final String rank;
    private final int value;

    public Card(String suit, String rank, int value) {
        this.suit = suit;
        this.rank = rank;
        this.value = value;
    }

    public String getSuit() {
        return suit;
    }

    public String getRank() {
        return rank;
    }

    public int getValue() {
        return value;
    }
    
    public String getImagePath()
    {
        return "./cards/" + toString() +".png";
    }

    @Override
    public String toString() {
        //return rank + " of " + suit;
        return rank+"-"+suit;
    }
    
}

