package blackjack;
/**
 *
 * @author daniel
 */
import java.util.*;
//This class was generated by Chat gpt
public class Deck
{
    private final List<Card> cards;

    public Deck() {
        cards = new ArrayList<>();
        initializeDeck();
        shuffle();
    }

    private void initializeDeck()
    {
        String[] suits = {"Hearts", "Diamonds", "Clubs", "Spades"};
        String[] ranks = {"2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"};
        int[] values = {2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10, 11};

        for (String suit : suits) {
            for (int i = 0; i < ranks.length; i++) {
                cards.add(new Card(suit, ranks[i], values[i]));
            }
        }
    }

    public void shuffle() // method to shuffle the cards
    {
        Collections.shuffle(cards);
    }

    public Card drawCard()
    {
        if (cards.isEmpty()) {
            initializeDeck();
            //shuffle();
        }
        return cards.remove(cards.size() - 1);
    }


}
