package blackjack;
/**
 *
 * @author daniel
 */
public abstract class Player { //This class was partly generated by Chat Gpt
    protected Hand hand;
    protected String name;

    public Player(String name) // player constructor 
    {
        this.name = name;
        this.hand = new Hand();
    }

    public void addCardToHand(Card card)// add card to player hand. Calls the add card method from Hand class.
    {
        hand.addCard(card);
    }

    public int getHandValue() // get total value of players hand. Calls the getValue mthod in Hand
    {
        return hand.getValue();
    }

    public Hand getHand() //returns hand object of player
    {
        return hand;
    }

    public String getName()// returns name of player
    {
        return name;
    }

    public abstract void play(Deck deck);// subclass of player must provide implementaion for this method
}

